apiVersion: v1
kind: Service
metadata:
  name: host-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: host-service
subsets:
  - addresses:
      - ip: 10.1.0.5  # Replace with your host's IP
    ports:
      - port: 8080
