apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: safekeeper
  namespace: neon
spec:
  serviceName: "safekeeper"
  replicas: 3
  selector:
    matchLabels:
      app: safekeeper
  template:
    metadata:
      labels:
        app: safekeeper
    spec:
      containers:
        - name: safekeeper
          image: neondatabase/neon:latest
          command:
            - "/bin/bash"
          args:
            - "-c"
            - |
              /usr/local/bin/safekeeper --id=$(echo ${POD_NAME##*-} | tr -d '-') --broker-endpoint=http://storage-broker-service.neon.svc.cluster.local:50051 --listen-pg=0.0.0.0:5454 --listen-http=0.0.0.0:7676 --advertise-pg=${POD_NAME}.safekeeper:5454
          ports:
            - containerPort: 5454
            - containerPort: 7676
          env:
            - name: DEFAULT_PG_VERSION
              value: "15"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  namespace: neon
  name: safekeeper
spec:
  clusterIP: None
  selector:
    app: safekeeper
  ports:
    - name: pg
      protocol: TCP
      port: 5454
      targetPort: 5454
    - name: http
      protocol: TCP
      port: 7676
      targetPort: 7676
