apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-broker
  namespace: neon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-broker
  template:
    metadata:
      labels:
        app: storage-broker
    spec:
      containers:
        - name: storage-broker
          image: neondatabase/neon:latest
          command:
            - "/usr/local/bin/storage_broker"
          args:
            - "--listen-addr=0.0.0.0:50051"
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: storage-broker-service
  namespace: neon
spec:
  selector:
    app: storage-broker
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
