# This rule is not used by the project neon-operator-go itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the neon.oltp.molnett.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: neon-operator-go
    app.kubernetes.io/managed-by: kustomize
  name: cluster-editor-role
rules:
- apiGroups:
  - neon.oltp.molnett.org
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neon.oltp.molnett.org
  resources:
  - clusters/status
  verbs:
  - get
