apiVersion: neon.oltp.molnett.org/v1alpha1
kind: Branch
metadata:
  labels:
    app.kubernetes.io/name: neon-operator-go
    app.kubernetes.io/managed-by: kustomize
  name: branch-sample
spec:
  projectID: project-sample
  pgVersion: 17
